##############################################################################
# Genome and project-specific files that will change from project-to-project
##############################################################################

# GTF file for the genome build you would like to use
gtf_file:
  /home/groups/CEDAR/anno/gtf/hg38_ens94_ERCC.gtf
# Bed file for rseqc function read_distribution
bed_file:
  /home/groups/CEDAR/anno/gtf/hg38_ens94.chr.bed
# Pre-built STAR index
star_index:
  /home/groups/CEDAR/anno/indices/star/hg38_ERCC
# Genome annotations file used for biotype analysis/QC
filter_anno:
  /home/groups/CEDAR/anno/biomaRt/hg38.Ens_94.biomaRt.geneAnno.Rdata

####################################################################
# Tool-specific files that will not change from project-to-project
####################################################################

# Fasta file including Illumina adapters to be trimmed out via bbduk
bb_adapter:
  ./data/adapters.fa
# Pre-built genome indexes for various organisms which we will screen against to 
# look for contamination
conf:
  /home/groups/CEDAR/tools/FastQ_Screen_Genomes/fastq_screen.conf
# Paths to various tools which are used in this pipeline
star_tool:
  /home/groups/CEDAR/tools/STAR/tags/2.5.3a/bin/Linux_x86_64/STAR

##############################################################################################
# Project-specific specifications you will need to make prior to submission of the pipeline
##############################################################################################

# Unique project identifier which will be concatenated onto your counts table file name.
project_id:
  project_id
# Genome assembly used for GO analysis.
# Format must be as below, with the genome assembly first, and the version of ensembl second, separated by a period
# (Unless there is only one ensembl version, then just write assembly)
assembly:
  hg38.94
# Metadata needed for differential expression analysis
omic_meta_data:
# tab delimited file
  /path/to/metadata.tsv
# desired expression threshold for estimating sequencing saturation (in FPKM)
expression_threshold:
  5
# Biotypes you would like to include in your gene counts table 
# Examples: protein_coding, lincRNA, sRNA, rRNA, snRNA, snoRNA, etc.
biotypes:
  protein_coding
# Remove mito genes (no = 0; yes = 1)
mito:
  1
# option to print GO term tree (no = 0; yes = 1)
printTree:
  1
# fold change cutoff (not log2 transformed) for GO analysis and volcano pot
FC:
  2
# FDR adjusted p-value cutoff for GO analysis and volcano plot
adjp:
  0.01
seq_layout:
  PE
# The column name of the characteristic you would like to do DE on
# Examples: Diagnosis, genotype, condition, etc.) 
# This must be a column in your omic_meta_data.
linear_model:
  Condition
# The column name in which your sampleIDs are defined in omic_meta_data (i.e., column 1)
# These should match the sampleIDs in your fastq files.
sample_id:
  SampleID
# The column names in your omic_meta_data file which you would like to annotate your heatmaps by. 
# This is used as a QC to look for batch effects. 
# Enter columns which could potentially introduce a batch effect in your data.
meta_columns_to_plot:
  Lane: Lane
  Condition: Condition
  Time: Time
pca:
  labels:
    #Column name in meta data file to generate group files and comparisons
    - Condition
    - Time
    - Lane
# Contrasts which you would like to run differential expression on.
# For example if you want to look at wild type (wt) vs. mutant (mut), you would specify mut-vs-wt
# It is important that when listing your types here, you write your baseline SECOND
diffexp:
  # contrasts to generate group files and perform comparisons
  contrasts:
    contrast-vs-baseline:
      - contrast
      - baseline
  # This option is specified if you would like to run DESeq2 on a subset of your samples (> pairwise comparison)
  LRT:
    - contrast1
    - contrast2
    - baseline
# Correlation test type to use for plotting sample-sample correlations.
# Options are Pearson, Spearman, or both.
correlation_test:
  both
# If you would like to colour your QC plots by an RColorBrewer palette, list that palette under the rcolorbrewer parameter, otherwise, write "NA"
# If you would like to colour your QC plots by specific colours, please list them under the discrete category, with one colour for each bullet point
# The discrete colours will be assigned to your Conditions (ie. linear_model) in the order that they show up in your metadata table, when it is ordered alphabetically by sample ID
# There must be the same number of colours listed as there are Conditions
# If no options are specified, the default ggplot2 colours are used
colors:
  rcolorbrewer:
    - NA
  discrete:
    - NA
