##########################################
# Important project-specific paths/files
##########################################

# Metadata needed for differential expression analysis
omic_meta_data:
  # tab delimited file
  /absolute/path/to/project/meta-data.txt

# Path to your base directory (path to this directory)
base_dir:
  /base/directory/of/project

##############################################################################
# Genome and project-specific files that will change from project-to-project
##############################################################################

# GTF file for the genome build you would like to use
gtf_file:
  /home/groups/CEDAR/estabroj/indexes/Mus_musculus/UCSC/mm10/Annotation/Archives/archive-2015-07-17-14-33-26/Genes/genes.gtf

# Bed file for rseqc function read_distribution
bed_file:
  /home/groups/CEDAR/estabroj/beta4/data/mm10_MGC_gene.bed

# Pre-built STAR index
star_index:
  /home/groups/CEDAR/estabroj/indexes/Mus_musculus/UCSC/mm10/Sequence/Star2Index


####################################################################
# Tool-specific files that will not change from project-to-project
####################################################################

# Fasta file including Illumina adapters to be trimmed out via bbduk
bb_adapter:
  /home/exacloud/lustre1/CompBio/estabroj/data/snakemake/projects/beta4/data/adapters.fa

# Pre-built genome indexes for various organisms which we will screen against to look for contamination
conf:
  /home/groups/CEDAR/tools/FastQ_Screen_Genomes/fastq_screen.conf

# Paths to various tools which are used in this pipeline
star_tool:
  /home/groups/CEDAR/tools/STAR/tags/2.5.3a/bin/Linux_x86_64/STAR


##############################################################################################
# Project-specific specifications you will need to make prior to submission of the pipeline
##############################################################################################

# Unique project identifier which will be concatenated onto your counts table file name.
project_id:
  {project-id}

# Genome assembly used for GO analysis, format must be as below, with the genome assembly first, and the version of ensembl second, separated by a period.
assembly:
  mm10

# The "baseline" used for your differential expression analysis. Ex: Healthy, WT, etc.
baseline:
  #Baseline for linear model - needs to be a factor in column listed for : linear_model
  38-KC

seq_layout:
  PE

# The column name of the characteristic you would like to do DE on. Example: Diagnosis, genotype, etc. This must be a column in your omic_meta_data.
linear_model:
  #Column name in meta data file to generate contrasts by
  Condition

# The column name in which your sampleIDs are defined in omic_meta_data. These should match the sampleIDs in your fastq files.
sample_id:
  #Column name listing unique sample ids to be used. This needs to be the first column in the meta data file
  SampleID

# The column names in your omic_meta_data file which you would like to annotate your heatmaps by. This is used as a QC to look for batch effects. Enter columns which could potentially introduce a batch effect in your data.
meta_columns_to_plot:
  Time: Time
  Condition: Condition
  Lane: Lane

pca:
  labels:
    #Column name in meta data file to generate group files and comparisons
    - Condition

diffexp:
  # contrasts to generate group files and perform comparisons
  contrasts:
    # baseline-vs-contrast:
    #   - contrast
    #   - baseline

    38-KC-vs-38-KC-B4:
      - 38-KC-B4
      - 38-KC

